import { RouterProvider } from "@tanstack/react-router"
import ReactDOM from "react-dom/client"
import { getRouter } from "./core/router"

const router = getRouter()

// biome-ignore lint/style/noNonNullAssertion: Code generated by vite
const rootElement = document.getElementById("app")!

if (!rootElement.innerHTML) {
  const root = ReactDOM.createRoot(rootElement)
  root.render(<RouterProvider router={router} />)
}
